### ISSUE TITLE
[Mobile] Integration of "login" and "logout" Operations with Backend

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#314] opened 2022-10-28 17:23 UTC
As discussed in the [Mobile Team Meeting](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE-Meeting-Notes-%233), I am assigned to integrate _login_ and _logout_ buttons with backend structure. I will simply divide this issue into two tasks: integrating login and integrating logout.

- [x] Integration of login buttons
- [x] Integration of logout buttons
- [x] Testing with backend structure

Deadline: 29/10/2022, 23:59
Reviewer: @atillaturkmen

**Comment by musasimsekdotdll** [comment] 2022-10-28 21:34
I have created a [branch](https://github.com/bounswe/bounswe2022group7/tree/dev/android/login-logout-integration) for this task.

**Comment by musasimsekdotdll** [comment] 2022-10-29 17:51
I added a task about testing connection between mobile with these changes and backend.

**Comment by musasimsekdotdll** [comment] 2022-10-29 17:56
I have completed the integration of login button. Changes can be reviewed in the [branch page](https://github.com/bounswe/bounswe2022group7/commits/dev/android/login-logout-integration) starting with _login endpoint added_ commit, which has SHA with value "ad4c960d4e4cc026072e0946872c4185e4b50ccf".

Once other group members complete the new branch architecture, I will open the according pull request.

**Comment by atillaturkmen** [comment] 2022-10-30 09:42
There are some errors in the implementation, specifically about back end responses. Login endpoint doesn't return an object but a token or nothing in case login was unsuccessful. Since there is no object returned, there is no status field either. This error also exists in the register function as I mentioned in the issue https://github.com/bounswe/bounswe2022group7/issues/335 but I will fix it. After changing the login function, feel free to open a pull request and add me as the reviewer.

**Comment by musasimsekdotdll** [comment] 2022-10-30 12:07
I ran the docker image in my local and I logged in to the app succesfully. I opened a [pull request](https://github.com/bounswe/bounswe2022group7/pull/340) and we can close this issue after that pull request is approved.

**Comment by atillaturkmen** [comment] 2022-10-31 11:27
I have checked the code and tested it. Login functionality works as intended. I have made some minor changes such as deleting commented out code and redundant imports. Then I merged the PR into develop branch. Therefore this issue can be closed.

**Closed by atillaturkmen** 2022-10-31 11:27 UTC
Labels: Status: In Progress, Priority: Medium, Difficulty: Medium, Type: Implementation, Target: Mobile
