### ISSUE TITLE
Implement the Home page endpoint integrations

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#351] opened 2022-10-31 10:40 UTC
As discussed in the [Mobile Team Meeting 3](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE-Meeting-Notes-%233), I was assigned to prepare the Home page  integration with the relevant endpoints.

Sub-tasks:
  - [x]  Branch out from the develop branch
  - [x]  Get Events and Art Items for the visitor users and list them on the home page
  - [x]  Get Events and Art Items for the registered users and list them on the home page
  - [x] Connect the route to the relevant pages
  - [x] Create a PR 

Deadline: 31/10/2022, 23:59
Reviewer: @canatakan

**Comment by AlicanM** [comment] 2022-10-31 15:32
I created Post class that contains the common information of events and art items, such as id, creator, title, description, imageUrl.
[relevent commit](https://github.com/bounswe/bounswe2022group7/commit/c0d157c3f19dd1d678a65b0f33d3dff85d99989a)

**Comment by AlicanM** [comment] 2022-10-31 15:39
[GET]homepage/getGenericArtItems, [GET]homepage/getGenericEvents, [GET]homepage/getEventsForUser, [GET]homepage/getArtItemsForUser method are connected with the home page.
When home page loads, it checks if the user is visitor or a registered user and calls coresponding methods. 
Returned event and an art item list are combine into a post list and displayed in the page.
[relevant commit1](https://github.com/bounswe/bounswe2022group7/commit/cbae513a774ddb1f901586e8e056cf95678d5ef1), [relevant commit2](https://github.com/bounswe/bounswe2022group7/commit/06db62d07bdd46e405f09edbbfea2cdd69e0fe38), [relevant commit3](https://github.com/bounswe/bounswe2022group7/commit/691508bd97a1c14aa784b374df2cf5c05abe6db3)

**Comment by AlicanM** [comment] 2022-10-31 18:38
Open and checked the commented art item parts. This issue is now ready to review. @canatakan

**Comment by canatakan** [comment] 2022-10-31 22:14
* I shared [my review](https://github.com/bounswe/bounswe2022group7/pull/362#pullrequestreview-1162617659) on your pull request #365.

* It is not possible to merge your code under these circumstances.

* Please check your code meticulously and be sure that it provides the necessary functionality.

**Comment by atillaturkmen** [comment] 2022-10-31 22:34
I have solved the conflicts in PR https://github.com/bounswe/bounswe2022group7/pull/365 and fixed the issues Atakan mentioned. Now the homepage works as intended. Thus, I merged the pull request and I am closing this issue.

**Closed by atillaturkmen** 2022-10-31 22:34 UTC
Labels: Status: In Progress, Priority: High, Difficulty: Medium, Type: Implementation, Target: Mobile
