### ISSUE TITLE
Review and Update the Sequence Diagram for Discussion Forum

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#312] opened 2022-10-28 15:03 UTC
According to [Meeting 1](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%231) after the reviews on class diagrams, I am going to update the [sequence diagram for DiscussionForum](https://github.com/bounswe/bounswe2022group7/wiki/Sequence-Diagrams#7---discussion-forum) which was originally done by Ali Can Milani. I implemented changes in the week of first meeting but the class diagram evolved even after that so I will do a one last review.

**Reviewer:**  @AlicanM 
**Deadline:** 28/10/2022 23.59

**Comment by demet47** [comment] 2022-10-28 15:20
After the first review requested in [meeting 1](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%231) the diagram became something like below:
![image](https://user-images.githubusercontent.com/64031659/198673388-28ffcc8e-e7fd-4251-ae81-6d761e38fd4f.png)

After the recent updates on class diagram, second revision turned it into a structure as below:
![Sequence diagram - 7  Discussion Forum](https://user-images.githubusercontent.com/64031659/198673623-e46d7ac1-4592-452a-99b3-2ba59fec925f.png)

**Comment by demet47** [comment] 2022-10-28 15:22
Final version can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Sequence-Diagrams#7---discussion-forum)

**Comment by AlicanM** [comment] 2022-10-31 15:27
Looks as intended, thanks for your work.
Closing the issue.

**Closed by AlicanM** 2022-10-31 15:27 UTC
Labels: Status: Pending Review, Difficulty: Medium, Type: Design
